In [1]:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

arr[3] = 6

print(arr)

[1 2 3 4 5]
[1 2 3 6 5]


In [2]:

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr)
rearr = arr.reshape(4, 3)
farr = rearr.flatten()
print(rearr)
print(farr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [3]:
import numpy as np
a1 = np.array([[1, 2], [3,4]])
a2 = np.array([[11, 22], [33,44]])
va=np.vstack((a1,a2))
ha=np.hstack((a1,a2))
print(va)
print(ha)

[[ 1  2]
 [ 3  4]
 [11 22]
 [33 44]]
[[ 1  2 11 22]
 [ 3  4 33 44]]


In [4]:


import numpy
arr = numpy.array([1, 5, 4, 8, 3, 7])
max = numpy.max(arr)
min = numpy.min(arr)
mean = numpy.mean(arr)
print('maximum element is: ',max)
print('minimum element is: ',min)
print('mean value is: ',mean)

maximum element is:  8
minimum element is:  1
mean value is:  4.666666666666667


In [5]:

import numpy as np
oarr= np.arange(1,10)
tarr=oarr.reshape(3,3)
print (tarr)
print(oarr)
rarr= oarr[::-1]
print (rarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
